### ISSUE TITLE
Opinion

### ISSUE THREAD

**Issue by tchaton** [ai4iacts/hexagdly#2]
Hello there,

I think you are into something.
I am sure it should outperform every other kernels.

The only issue is the speed.
It would be interesting to have a highly low level implementation of this in Cuda or Cudnn, or even Tensor Comprehension.

Best.
T.C

**Comment by tchaton** [comment]
Hello guys,

It might be possible to implement a faster hexa con2d.
You interpolate the hexa to grid.
Then you apply a regular convolution over it, and interpolate it back to a hexa.

Best,
T.C

**Comment by holchtim** [comment]
Hi @tchaton ,
a low level implementation would indeed be interesting, especially Tensor Comprehension!  We will definitely have a look into that.
Regarding the interpolation idea: We are currently working on a notebook with a comparison between different kernels and data representations (including interpolation) to provide a performance benchmark. The problem with interpolation is that it can introduce more or less severe sampling artefacts which can destroy or at least distort important features in the data. This effect can be reduced by increasing the resolution, but this again increases the amount of data points to process, resulting in longer training and evaluation times which can quickly exceed the computational overhead caused by the hex-kernel implementation.

**Comment by fsalmasri** [comment]
Hello, 

Any update regarding the optimization procedure. it should definitely attract more experience.
